### ISSUE TITLE
Why is the line commented?

### ISSUE THREAD

**Issue by g-yui** [acidicoala/dream-api#10]
https://github.com/acidicoala/dream-api/blob/68cca8c11ead17341002cdacce443d58bacf1004/src/setup/registry.py#L31
Just out of curiosity, is it for a further release?  Since the value for it in the set_reg 'Proxy_Enable' later on is 0.

**Comment by acidicoala** [comment]
Imagine DreamAPI has crashed or its process was killed. The result would be that the Proxy is left enabled. To fix that I suggest people to simply open the DreamAPI again and shut it down properly. Now, if we were to save & restore the enabled state, that would mean that DreamAPI would not disable the Proxy when shutting down DreamAPI in this case, thus leaving users with lost network connection once again.

**Comment by g-yui** [comment]
Oh I see, is the line necessary in the code then?

**Comment by acidicoala** [comment]
Technically no, it's just a comment :) I left it just in case it might be useful in the future.
For example, what if someone was using some sort of proxy for other purposes? Turning proxy off instead of restoring previous proxy state might present an issue in this case.
So either strategy has its own drawbacks, so I chose the one which is appropriate for most users.

**Comment by g-yui** [comment]
Gotcha :D
