### ISSUE TITLE
Question/Enhancement - Adding and blacklisting DLCs via GUI

### ISSUE THREAD

**Issue by g-yui** [acidicoala/dream-api#11]
I've been fiddling around with the fork and I felt like adding the option of a GUI to Add or Blacklist certain DLCs, as opposed to do it manually from the json file.

The issue is that I'm not particularly good with Json files and I have no clue how to parse them and append the user-provided info to the appropriate location, could you help me figure it out?

Here's the code for the function itself:

```
def retrieve():
    # Temporary variables, these were made in order to debug and check the values # 
    if game_entry.get() == 'Game Name' or None:
        no_game_name = 1
    if dlc_entry.get() == 'DLC Name' or None:
        no_dlc_name = 1
    if id_entry.get() == 'DLC ID' or None or len(id_entry.get()) < 10:
        from tkinter import messagebox 
        messagebox.showerror("Error", "Invalid DLC ID, please try again")
        root.destroy()
        dlc_add()
    if platform_entry.get() == "Platform" or None:
        default_platform = 1
    if entry_type.get() == 'Entry type' or None:
        default_entry = 1

    # Here would go the json indexing and appending, IF I HAD ONE!!! 😢 #

def dlc_add(): # They are globals only because I felt too lazy to add them as None 😝 #
    global root
    root = Tk()
    root.title('Add or remove a DLC')
    root.iconbitmap(str(get_bundle_path('icon.ico')))
    root.minsize(250, 150)
    global game_entry
    game_entry = Entry(root, width=30, justify=CENTER)
    game_entry.insert(0, 'Game Name')
    game_entry.pack(padx=5, pady=5)

    global dlc_entry
    dlc_entry = Entry(root, width=30, justify=CENTER)
    dlc_entry.insert(0, 'DLC Name')
    dlc_entry.pack(padx=5, pady=5)

    global id_entry
    id_entry = Entry(root, width=30, justify=CENTER)
    id_entry.insert(0, 'DLC ID')
    id_entry.pack(padx=5, pady=5)

    global platform_entry
    platform_list = ["Epic"] # I thought about adding Origin but that origin-entitlements.json file scares me # 
    platform_entry = Combobox(root, width=30, justify=CENTER, values=platform_list)
    platform_entry.set("Platform")
    platform_entry.pack(padx=5, pady=5)

    global entry_type
    entry_list = ["Add", "Blacklist"]
    entry_type = Combobox(root, width=30, justify=CENTER, values=entry_list)
    entry_type.set('Entry type')
    entry_type.pack(padx=5, pady=5)

    button_root = Button(root, width=20, text="Apply", command=retrieve)
    button_root.pack(padx=5, pady=5)

    button_root2 = Button(root, width=20, text="Cancel", command=root.destroy)
    button_root2.pack(padx=5, pady=5)

    # Quality of life, non-essential addition, if this makes the program too bloated feel free to remove it
    import webbrowser
    def callback(url):
        webbrowser.open_new(url)

    link = Label(root, text="Get DLC ID's", foreground="blue", cursor="hand2")
    link.pack(padx=5, pady=5)
    link.bind("<Button-1>", lambda e: callback("https://scream-db.web.app/"))

    # This can clearly be optimized, but I couldn't figure out how at the time 
    root.update_idletasks()

    # Get screen size
    w = root.winfo_screenwidth()
    h = root.winfo_screenheight()

    # Get windows size and calculate offset
    size_x, size_y = root.geometry().split('+')[0].split('x')
    x = int(w / 2 - int(size_x) / 2)
    y = int(h / 2 - int(size_y) / 2)

    # Finally, apply it
    root.geometry(f'{size_x}x{size_y}+{x}+{y}')

    root.mainloop()
```

And here's the added button to the main ApplicationWindow (I also changed it's minsize to (300,225) to accommodate for the new button)

`
Button(
            self.frame,
            text="Add or Blacklist DLCs",
            takefocus=False,
            command=dlc_add
        ).pack(pady=8)
`

**Comment by acidicoala** [comment]
You can have a look at `__get_config_json` function that loads json from the disk. https://github.com/acidicoala/dream-api/blob/da8c012a3f9a3cf6da351d77a29da1af9ad41885/src/setup/config.py#L83

In short, python has standard library methods for loading json files. Json is loaded into a `dict`, from which you can access its members using the indexing operator `[]`. For example:
https://github.com/acidicoala/dream-api/blob/2ce50a66f20134afe4f1111926ad17abb5a5986f/src/mitm/addons/origin.py#L63

Then you do all the modifications to that dict. This is something that goes beyond json, so if you are struggling here, you have to learn more about python dicts.

When finished, you serialize that dict into a string and save it on the disk like it is done here:
https://github.com/acidicoala/dream-api/blob/438172e055cc5d31ede7a5a8ff7899df7caff4df/src/setup/config.py#L101

**Comment by acidicoala** [comment]
To be honest, even GUI for adding DLC IDs isn't going to help much in my opinion, because users still have to spend time searching for that ID, which typically takes more time than just copy pasting it into the config file.

A really useful addition instead would be the DLC search by its name. This is completely and easily doable with Epic, and to a certain extent with origin. So the end user will only have to type in the name of that DLC, which can be incomplete since search engine at Epic servers will take care of that. Then the GUI can take the ID from that DLC and add to the blacklist.

Epic has deployed GraphQL endpoint for its services, which makes it very convenient to adapt for custom queries. Take a look at this query that searches for games:
https://github.com/acidicoala/ScreamDB/blob/43261588d3df820c32d34c5043efc0edc25ee404/graphql/queries.graphql#L1

For DLCs, you would only need to change the `category` to  `addons|digitalextras`. You will need to learn a little bit about GraphQL to implement that of course, so it's up to you really. But you can visit any DLC page on Epic Games store with your browser's dev tools open and inspect the network traffic to see how those queries are formed. [Example DLC page](https://www.epicgames.com/store/en-US/all-dlc/cities-skylines?sortBy=relevance&sortDir=DESC&pageSize=30). [Example GraphQL response](https://ibb.co/wYRL8VP). As you can see, all data is transmitted via JSON files, which makes it just as easy to implement in python as it is in JavaScript/TypeScript.

P.S. I will be soon releasing another project with no GUI. It also has a config file, which is more complex than the one in DreamAPI. If you are looking for ways to practice python/GUI, I would suggest instead to work on that one. There you will have the freedom to build a UI without having to conform to the coding standards that I impose here :)
Because I already see a lot of global variables, and weird code like this:
```python
    def callback(url):
        webbrowser.open_new(url)
    #...
    link.bind("<Button-1>", lambda e: callback("https://scream-db.web.app/"))
```

Why add a wrapper function if you are already using a lambda? Here is equivalent code:
```python
    link.bind("<Button-1>", lambda e: webbrowser.open_new("https://scream-db.web.app/"))
```

**Comment by g-yui** [comment]
Oh believe me, I will ;)
Also I added weird code due to my own inexperience, I really haven't taken as much of a deep look into how Python works as I should, since I'm doing this for fun and I like learning by just making stuff, matter of fact, I've learned quite a lot through this and the ScreamGUI, I'll take a look if I can just add via GraphQL as I agree with you, it'd be quite the QoL improvement to this already great tool.

**Comment by acidicoala** [comment]
What languages are you more comfortable with?

**Comment by g-yui** [comment]
Thus far, only C++ and Python, both of which I'm learning bit by bit, though libraries like polyhook2 just fly over my head and I've yet to make a header file myself, though I can use them and I understand the basics of it.
